### ISSUE TITLE
Greater status tracking/error handling 

### ISSUE THREAD

**Issue by cvxluo** [cvxluo/item-index-website#6]
- [ ] Upload status for images
- [ ] Confirmation that edits go through
- [ ] Confirm valid file types and tag edits
